<!DOCTYPE JMdict [
  <!ELEMENT entry (ent_seq, k_ele*, r_ele+, sense+)>
  <!ELEMENT ent_seq (#PCDATA)>
  <!ELEMENT k_ele (keb, ke_inf*, ke_pri*)>
  <!ELEMENT keb (#PCDATA)>
  <!ELEMENT ke_inf (#PCDATA)>
  <!ELEMENT ke_pri (#PCDATA)>
  <!ELEMENT r_ele (reb, re_nokanji?, re_restr*, re_inf*, re_pri*)>
  <!ELEMENT reb (#PCDATA)>
  <!ELEMENT re_nokanji (#PCDATA)>
  <!ELEMENT re_restr (#PCDATA)>
  <!ELEMENT re_inf (#PCDATA)>
  <!ELEMENT re_pri (#PCDATA)>
  <!ELEMENT sense (stagk*, stagr*, pos*, xref*, ant*, field*, misc*, s_inf*, lsource*, dial*, gloss*)>
  <!ELEMENT stagk (#PCDATA)>
  <!ELEMENT stagr (#PCDATA)>
  <!ELEMENT xref (#PCDATA)*>
  <!ELEMENT ant (#PCDATA)*>
  <!ELEMENT pos (#PCDATA)>
  <!ELEMENT field (#PCDATA)>
  <!ELEMENT misc (#PCDATA)>
  <!ELEMENT lsource (#PCDATA)>
  <!ATTLIST lsource xml:lang CDATA "eng">
  <!ATTLIST lsource ls_type CDATA #IMPLIED>
  <!ATTLIST lsource ls_wasei CDATA #IMPLIED>
  <!ELEMENT dial (#PCDATA)>
  <!ELEMENT gloss (#PCDATA | pri)*>
  <!ATTLIST gloss xml:lang CDATA "eng">
  <!ATTLIST gloss g_gend CDATA #IMPLIED>
  <!ELEMENT pri (#PCDATA)>
  <!ELEMENT s_inf (#PCDATA)>

  <!ENTITY adj-no "nouns which may take the genitive case particle 'no'">
  <!ENTITY n "noun (common) (futsuumeishi)">
]>
<JMdict>
  <entry>
    <ent_seq>1171270</ent_seq>
    <k_ele>
      <keb>右翼</keb>
      <ke_pri>ichi1</ke_pri>
      <ke_pri>news1</ke_pri>
      <ke_pri>nf04</ke_pri>
    </k_ele>
    <r_ele>
      <reb>うよく</reb>
      <re_pri>ichi1</re_pri>
      <re_pri>news1</re_pri>
      <re_pri>nf04</re_pri>
    </r_ele>
    <sense>
      <pos>&adj-no;</pos>
      <gloss>right-wing</gloss>
      <gloss xml:lang="fr">aile droite (oiseau, armée, parti politique, base-ball)</gloss>
      <gloss xml:lang="ru">пра́вое крыло́</gloss>
      <gloss xml:lang="ru">пра́вый фланг</gloss>
      <gloss xml:lang="de">die Rechte</gloss>
      <gloss xml:lang="de">rechter Flügel</gloss>
    </sense>
    <sense>
      <pos>&n;</pos>
      <gloss>right field (e.g. in sport)</gloss>
      <gloss>right flank</gloss>
      <gloss>right wing</gloss>
      <gloss xml:lang="de">{Sport}</gloss>
      <gloss xml:lang="de">rechte Flanke</gloss>
      <gloss xml:lang="de">rechter Flügel</gloss>
    </sense>
  </entry>
</JMdict>
